name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          cd tests
          cd RoadmapCreationAssistance.API.Tests    
          dotnet test

  pushImageToDockerHub:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    outputs:
      image-tag: ${{ steps.datetime.outputs.now }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get current datetime
        id: datetime
        run: echo "now=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        
      - name: Build and tag image
        run: |
          docker build \
            -t ${{ vars.DOCKERHUB_USERNAME }}/roadmap-creation-assistance:${{ steps.datetime.outputs.now }} \
            .

      - name: Login to Docker Hub
        run: docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/roadmap-creation-assistance:${{ steps.datetime.outputs.now }}

  deployToAzureContainerApp:
    name: Deploy to Azure Container App
    runs-on: ubuntu-latest
    needs: pushImageToDockerHub
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ROADMAPCREATIONASSISTANCE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ROADMAPCREATIONASSISTANCE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ROADMAPCREATIONASSISTANCE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ vars.DOCKERHUB_USERNAME }}/roadmap-creation-assistance:${{ needs.pushImageToDockerHub.outputs.image-tag }} \
            --cpu 0.5 \
            --memory 1.0Gi \
            --replace-env-vars \
              DD_API_KEY=${{ secrets.DD_API_KEY }} \
              DD_SITE=us3.datadoghq.com \
              DD_SERVICE=roadmap-creation-assistance \
              DD_ENV=production \
              DD_VERSION=${{ needs.pushImageToDockerHub.outputs.image-tag }} \
              DD_TRACE_ENABLED=true \
              DD_RUNTIME_METRICS_ENABLED=true \
              DD_TRACE_AGENT_URL=https://trace.agent.us3.datadoghq.com \
              DD_CIVISIBILITY_AGENTLESS_ENABLED=true \
              LD_PRELOAD=/dd_tracer/dotnet/linux-musl-x64/Datadog.Linux.ApiWrapper.x64.so